version: "3"
services:
  dataCopy:
    image: busybox
    command: /bin/sh -c "echo cleaning && rm -rf /data/* && ls -la /data/ && echo copying && cp -r /data-live/* /data/ && ls -la /data/ && echo touching && touch /data/COPY_FINISHED && ls -la /data/"
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    volumes:
      - "/var/docker/data/bulibot-staging:/data"
      - "/var/docker/data/bulibot:/data-live:ro"
  
  bulibot:
    image: chrgroth/bulibot:${DOCKER_TAG:?please export DOCKER_TAG}
    command: ./waitForDataToBeCopied.sh
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bulibot-staging.rule=Host(`xxx`)"
        - "traefik.http.routers.bulibot-staging.entryPoints=websecure"
        - "traefik.http.routers.bulibot-staging.tls=true"
        - "traefik.http.services.bulibot-staging-svc.loadbalancer.server.port=8080"
    environment:
      - "NINJA_MODE=test"
    volumes:
      - "/var/docker/data/bulibot-staging:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - global_router
networks:
  global_router:
    external: true
